version: '3'
services:

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: christexe/php:7.4-fpm-alpine
    container_name: boxbilling
    restart: unless-stopped
    tty: true
    environment:
      - BASE_URL=http://localhost:8004/
      - DB_HOST=db
      - DB_NAME=boxbilling2
      - DB_USER=root
      - DB_PASS=passboxbilling
    working_dir: /var/www/html
    volumes:
      - ./public/:/var/www/html
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8004:80"
    volumes:
      - ./public/:/var/www/html
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - default

  db:
    image: mysql:5.7
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    user: root
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=passboxbilling
      - MYSQL_DATABASE=boxbilling2
      - MYSQL_USER=boxbilling
      - MYSQL_PASSWORD=passboxbilling

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8282:80
    links:
      - db:db
    restart: always
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=passboxbilling
    depends_on:
      - db